server:
  port: 8081


  #JDBC datasource
#spring:
#  datasource:
#    hikari:
#      driver-class-name: oracle.jdbc.OracleDriver
#      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
#      username: kimjisoo
#      password: pass

#JDBC spy datasource
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.ch0kog84exlz.ap-northeast-2.rds.amazonaws.com:3306/Trendy_Devs
    username: Trendy_Devs
    password: koreait123

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        include: health  # /actuator/health 엔드포인트를 노출합니다.
  endpoint:
    health:
      show-details: always  # 상세 정보를 항상 표시합니다.



#    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
#      username: kimjisoo
#      password: pass